import { writeFileSync, existsSync, unlinkSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'
import { randomUUID } from 'node:crypto'

export interface HookInjectionResult {
  /** Injected startup args */
  args: string[]
  /** Temp file paths to delete on agent exit */
  hookFiles: string[]
}

interface BuildHookArgsOptions {
  /** Agent working directory (for gemini-cli) */
  cwd?: string
}

/**
 * Injects a hook into the startup args for the given agent type and returns the result.
 * Generated temp files are listed in hookFiles.
 * Call cleanupHookFiles() after the agent exits.
 */
export function buildHookArgs(
  agentType: string,
  baseArgs: string[],
  hookCommand: string,
  options: BuildHookArgsOptions = {},
): HookInjectionResult {
  switch (agentType) {
    case 'claude-code':
      return buildClaudeCodeHook(baseArgs, hookCommand)
    case 'gemini-cli':
      return buildGeminiHook(baseArgs, hookCommand, options.cwd)
    case 'codex':
      return buildCodexHook(baseArgs, hookCommand)
    default:
      return { args: baseArgs, hookFiles: [] }
  }
}

function buildClaudeCodeHook(baseArgs: string[], hookCommand: string): HookInjectionResult {
  const settings = {
    hooks: {
      PostToolUse: [
        {
          matcher: '',
          hooks: [{ type: 'command', command: hookCommand }],
        },
      ],
    },
  }
  return {
    args: [...baseArgs, '--settings', JSON.stringify(settings)],
    hookFiles: [],
  }
}

function buildGeminiHook(
  baseArgs: string[],
  hookCommand: string,
  cwd?: string,
): HookInjectionResult {
  const projectDir = cwd ?? process.cwd()
  const geminiDir = join(projectDir, '.gemini')
  const settingsPath = join(geminiDir, 'settings.local.json')

  // Skip writing if the file already exists to protect the user's existing config
  if (existsSync(settingsPath)) {
    return { args: baseArgs, hookFiles: [] }
  }

  const settings = {
    hooks: {
      AfterTool: [
        {
          matcher: '',
          hooks: [{ type: 'command', command: hookCommand }],
        },
      ],
    },
  }

  mkdirSync(geminiDir, { recursive: true })
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2))

  return { args: baseArgs, hookFiles: [settingsPath] }
}

function buildCodexHook(baseArgs: string[], hookCommand: string): HookInjectionResult {
  const codexHome = process.env.CODEX_HOME ?? join(homedir(), '.codex')
  mkdirSync(codexHome, { recursive: true })
  const profileName = `mav-hook-${randomUUID()}`
  const tomlPath = join(codexHome, `${profileName}.config.toml`)

  const tomlContent = [
    '[hooks.post_tool_use]',
    `cmd = ${JSON.stringify(hookCommand)}`,
    'timeout_seconds = 10',
  ].join('\n')

  writeFileSync(tomlPath, tomlContent)

  return {
    args: [...baseArgs, '--profile-v2', profileName],
    hookFiles: [tomlPath],
  }
}

/**
 * Deletes temp files generated by buildHookArgs.
 * Call this when the agent process exits.
 */
export function cleanupHookFiles(hookFiles: string[]): void {
  for (const f of hookFiles) {
    try {
      if (existsSync(f)) unlinkSync(f)
    } catch {
      // Ignore deletion failures (file may already be gone)
    }
  }
}
